### ISSUE TITLE
Horizontal logs break without natural leaves

### ISSUE THREAD

**Issue by joeyleesi** [magneticflux-/fabric-tree-chopper#66]
## Expected Behavior

Only logs connected to natural leaves will be affected by tree chopper when `"requireLeavesToChop": true` is present in config.

## Current Behavior

When logs are placed horizontally connected and facing up/down tree chopper sometimes activates breaking all connected logs regardless of leaves touching.

## Steps to Reproduce

1. Place logs horizontally touching and facing up/down
2. Break a few logs with axe

## Additional Context

**Mod Version:** 0.8.0
**Minecraft Version:** 1.18.1
**Side:** Server

### Video for reference:
https://user-images.githubusercontent.com/98718890/151724348-f244bade-ebd8-4137-8aee-996ac36d554f.mp4

**Comment by magneticflux-** [comment]
Hmm... that is very strange! Do you have a way to consistently reproduce this, or any more detail about the surrounding environment? Were there leaves nearby, or there just before breaking?

I would also like the log file so I know what mods and versions were being used in case this is an incompatibility with something.

**Comment by magneticflux-** [comment]
I believe this issue was introduced in my fix for #25 and manifests when many trees are grown in the same place and then logs are placed where the trees used to be.

I have added an expiry after a certain number of ticks so logs that were touching leaves more than 10 seconds ago no longer count as touching leaves. This 10 second timer is reset each time a log in the tree is chopped, so it shouldn't affect users with `treeChopMode = SINGLE_CHOP`.
